---
title: "mod3_peer_review_Mohammad_Prasetyo"
output:
  html_document:
    df_print: paged
---

# ---------------------------------------------------
# Introduction to Business Analytics with R 
Create datetime object d that stores today's date, then convert it to "%m/%d/%Y" format.
```{r}
d <- Sys.Date()
d <- format(d, "%m/%d/%Y")
d
```
\
Check data type of d
```{r}
class(d)
```
\
Install & load lubridate package
```{r}
#install.packages("lubridate")
library(lubridate)
```

\
Extract the year, month, week, and day from d
```{r}
#Convert d to date type
d <- mdy(d)

d_year <- year(d) #Extract year
d_month <- month(d) #Extract month
d_week <- week(d) #Extract week
d_day <- day(d) #Extract day

#Print results
cat("Current year: ", d_year, 
    "\nCurrent month: ", d_month,
    "\nCurrent week: ", d_week,
    "\nCurrent day: ", d_day)
```
\
get the date 25 days from now, then assign as d_25 variable
```{r}
d_25 <- d + 25
cat("The date 25 days from now: ", format(d_25, "%m/%d/%Y"))
```
\
Calculate the difference between d and d_25
```{r}
dt <- difftime(d_25, d)
cat("The difference between d and d_25: ", as.numeric(dt), " days")
```

