---
title: "Spatial Figures Peer Review"
output: html_document
---
# Mohammad Prasetyo

## Problem 1

```{r problem_1_data,include=FALSE}

library(tidyverse)
library(maps)

####make some data for painting the map

my_world_map <- map_data("world")

countries <- unique(my_world_map$region)

set.seed(987)
some_data_values <- data.frame(

  "region"=countries,
  
  "Score"=runif(252,0,100))

```

```{r problem_1,echo=FALSE,message=FALSE}

map2 <- left_join(my_world_map, some_data_values)

ggplot(map2,aes(x=long, y=lat, group=group, fill=Score)) +
geom_polygon() +
scale_fill_distiller(palette=5)
```

## Problem 2

```{r problem_2_data,include=FALSE}

#####DO NOT MODIFY THIS CHUNK
set.seed(15)
Measurement<-rnorm(32,50,1)
```


```{r solution_p2,echo=FALSE,message=FALSE}
region_map <- filter(my_world_map, region %in% c("Costa Rica", "Panama", "Nicaragua"))
city_pop <- filter(world.cities, (country.etc %in% region_map$region) & (pop > 40000))
city_pop$Measurement <- Measurement

ggplot(region_map, aes(x=long, y=lat, group=group)) +
geom_polygon(fill="white", color="black") +
geom_point(data=city_pop, aes(x=long, y=lat, group=NULL, color=Measurement), size=5) +
scale_color_distiller(palette=7)
```

## Problem 3

```{r problem_3_data,include=FALSE}

#####INSTALL THESE PACKAGES IF NECESSARY
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)

####DO NOT MODIFY
s_america<-ne_countries(scale="medium",continent='south america',returnclass="sf")

```

```{r problem3,echo=FALSE}
s_america<-ne_countries(scale="medium",continent='south america',returnclass="sf")
ggplot(s_america) +
geom_sf(aes(fill=pop_est)) +
scale_fill_distiller(palette=10)

```


